server:
  port: 8080

spring:
  application:
    name: board
  config:
    activate:
      on-profile:

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    database: mysql


jwt:
  issuer :
  secret_key :


logging:
  config: classpath:logback-spring-local.xml
  level:
    org.hibernate.sql: debug
